interface ImportMeta {
  env: {
    VITE_APP_FIRESTORE_APIKEY?: string;
    VITE_APP_FIRESTORE_AUTHDOMAIN?: string;
    VITE_APP_FIRESTORE_PROJECTID?: string;
    VITE_APP_FIRESTORE_STORAGEBUCKET?: string;
    VITE_APP_FIRESTORE_MESSAGINGSENDERID?: string;
    VITE_APP_FIRESTORE_APPID?: string;
    VITE_APP_FIRESTORE_MESUREMENTID?: string;
    VITE_APP_NAVER_CLIENT_ID?: string;
    VITE_APP_NAVER_CLIENT_SECRET?: string;
  };
}
